version: '3.8'
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        volumes:
            - .:/app
        depends_on:
            - db

    db:
        image: mysql:8.3
        restart: always
        environment:
            MYSQL_DATABASE: admin
            MYSQL_USER: root
            MYSQL_PASSWORD:
            MYSQL_ROOT_PASSWORD:
        volumes:
            - ./storage/dbdata:/var/lib/mysql
